export const atlasNavigationStyles = `
:root{--sidebar:280px}html,body{height:100dvh;font-size:13px;letter-spacing:0}button,input,select{letter-spacing:0}
.topbar{height:54px;padding:0 16px;gap:16px}.brand{font-size:14px}.brand small{letter-spacing:0}.brand-icon{height:30px;width:30px}.top-actions select{display:none}.top-actions{gap:4px}.top-actions button{font-size:13px;min-height:44px}
#album{height:calc(100dvh - 54px)}.section-head{padding:14px 12px 8px}.section-head h1{font-size:16px;margin:0}.left-tabs{margin:4px 8px 8px}.tree-label{font-size:13px;font-weight:400;line-height:1.35}.object-tree-row.selected .tree-label{font-weight:500}.tree-arrow{min-height:44px}.left-footer{padding:8px}.left-footer button{font-size:12px}
.pgs-icon{width:19px;height:19px;stroke-width:1.7;flex:none;vertical-align:middle}.pgs-label-button{display:inline-flex;align-items:center;justify-content:center;gap:7px}
.toolbar{inset:12px 12px auto;display:flex;flex-wrap:nowrap;align-items:center;gap:0;background:white;border:1px solid var(--line);border-radius:6px;box-shadow:0 3px 12px #1735410b;pointer-events:auto;width:max-content;max-width:calc(100% - 24px)}
.toolbar .toolside{display:contents}.toolbar .toolgroup{border:0;box-shadow:none;padding:0;background:transparent}.toolbar .toolgroup button{height:44px;min-width:44px;padding:8px 12px;font-size:13px;border-radius:4px}.toolbar .tool-right{position:static;flex-shrink:1}.toolbar .tool-right button{min-width:44px}.toolbar .view-tools,.toolbar .camera-tools{display:none}.toolbar #navToggle{width:auto;min-width:44px}.toolbar #moreToggle{width:44px;padding:0}.toolbar #pgs-properties{border-left:1px solid var(--line)}
#pgs-camera-menu{position:absolute;top:64px;left:12px;z-index:15;display:flex;padding:5px;background:white;border:1px solid var(--line);border-radius:6px;box-shadow:var(--shadow);gap:4px}#pgs-camera-menu button{font-size:13px}#pgs-view-tools{display:flex;flex-wrap:wrap;gap:4px;margin-bottom:12px}#pgs-view-tools button{font-size:13px}
#stage{inset:0}#canvas:not([data-frame]){opacity:0}.statusbar{display:none}.scene-caption{inset:auto 12px 12px;max-width:720px;padding:10px 12px;gap:8px;border-radius:6px;box-shadow:0 3px 12px #1735410b}.caption-text h2{font-size:14px;line-height:1.3;margin:0;font-weight:500}.scope-title{align-items:center;gap:6px}#upOneLevel{font-size:12px;min-width:44px;min-height:44px;padding:4px}.page-move{display:none}#pageHint{display:none}#breadcrumb{display:none}#pgs-path{font-size:12px;color:var(--muted);display:flex;gap:8px;align-items:center;min-width:0;margin-top:3px}#pgs-path button{min-height:28px;padding:2px 0;border:0;background:none;font-size:12px;color:var(--muted);text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#pgs-clear{margin-left:auto;flex:none;color:var(--accent)!important}#pgs-path .pgs-path-open{width:32px;min-height:28px;padding:2px}
#pgs-album-list{display:flex;flex-direction:column;gap:0}#pgs-album-list button{border:0;border-bottom:1px solid var(--line);border-radius:0;display:grid;grid-template-columns:24px minmax(0,1fr) auto;gap:12px;align-items:center;text-align:left;padding:12px 4px;font-size:14px;background:none}#pgs-album-list button[aria-current=true]{color:var(--accent);background:#f0f6f6}#pgs-album-list small{font-size:11px;color:var(--muted);font-variant-numeric:tabular-nums}#pgs-album-open{width:100%;justify-content:space-between;margin-bottom:10px;font-size:13px;background:var(--paper)}
.right{inset:66px 12px auto auto;width:340px;max-height:min(560px,calc(100% - 180px));min-height:0;border-radius:6px}.prop-top{padding:6px 10px}.prop-top>span{font-size:13px}.prop-top #cardDrawing{display:none}#properties{padding:12px}#properties h2{font-size:16px;font-weight:500}.field{font-size:13px}.field label{font-size:12px}.floating-panel,#clipPanel{top:66px;right:12px;width:300px;max-height:calc(100% - 166px);border-radius:6px}.floating-panel h3{font-size:14px}.floating-panel label{font-size:13px}#sceneLoading{top:76px;max-width:calc(100% - 24px)}
#drawingPanel{inset:54px 0 0}.drawingbar{min-height:58px;padding:8px 16px}.drawingbar strong{font-size:16px;font-weight:500}.drawingbar span{font-size:12px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.drawinglayout{grid-template-columns:240px minmax(0,1fr)}.drawingbody{padding:16px;display:flex;flex-direction:column;min-height:0}.drawingbody h2{font-size:15px;font-weight:500}.source-link{font-size:13px}.source-link[aria-current=true]{border-color:var(--accent);background:#edf5f5}.pgs-source-role{display:block;color:var(--muted);font-size:11px;margin-top:3px}#drawingInfo{font-size:12px;margin:0 0 8px}#drawingResource{min-height:0;flex:1}.pgs-drawing-viewport{width:100%;min-height:200px;max-height:none}.pgs-drawing-viewport>a{width:100%;max-width:none;display:block}#drawingResource .pgs-drawing-viewport img{width:100%;min-height:200px;height:auto;object-fit:contain}.pgs-drawing-actions{gap:6px;margin-bottom:8px}.pgs-drawing-actions>a,.pgs-drawing-actions>button{font-size:12px;padding:8px}.pgs-drawing-search{width:100%;font-size:16px;margin-bottom:8px}#pgs-source-results{overflow:auto;min-height:0}.pgs-doc-search{display:block;width:100%;margin:0 0 12px;font-size:16px}.pgs-documents-search{width:100%;margin-top:10px;font-size:13px}
@media(max-width:800px){
 .topbar{padding:0 10px;gap:8px}.brand{font-size:13px;gap:8px}.brand small{font-size:11px}.top-actions #help{display:none}.top-actions #documents{display:none}.top-actions button{padding:8px;font-size:13px}.top-actions #pgs-albums{display:inline-flex}
 .left{top:54px;width:min(340px,calc(100vw - 24px));bottom:env(safe-area-inset-bottom,0px)}.left-tabs button{font-size:13px}.tree-label{font-size:14px}.tree-arrow{min-width:44px;flex-basis:44px}.section-head{padding:12px}.section-head h1{font-size:16px}input,select{font-size:16px}
 .toolbar{inset:8px 8px auto;width:calc(100% - 16px);max-width:none;justify-content:space-between;gap:0}.toolbar .toolgroup{flex:1}.toolbar .toolgroup.tool-right{flex:3;justify-content:space-between}.toolbar .toolgroup button{font-size:13px;padding:6px 8px;gap:5px;min-height:44px}.toolbar .toolgroup:first-child{flex:1}.toolbar #navToggle{width:44px;padding:0}.toolbar #navToggle span,.toolbar #pgs-camera span,.toolbar #pgs-properties span{display:none}.toolbar #drawing{flex:1}.toolbar #pgs-camera{width:44px;padding:0}.toolbar #pgs-properties{width:44px;padding:0}.toolbar #moreToggle{width:44px;padding:0}
 .scene-caption{inset:auto 8px calc(8px + env(safe-area-inset-bottom,0px));padding:8px 10px;max-width:none}.caption-text h2{font-size:14px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.scope-title{align-items:center}#pgs-path{font-size:12px}#pgs-path button{min-height:44px;min-width:44px}#pgs-path button:first-child{flex:1}#pgs-clear{min-width:44px!important}#upOneLevel{min-width:44px;max-width:44px;font-size:0}#upOneLevel:before{content:'↑';font-size:19px}#pgs-path .pgs-path-open{min-width:44px;min-height:44px}
 .right{inset:auto 8px calc(104px + env(safe-area-inset-bottom,0px));width:auto;max-width:none;max-height:min(320px,calc(40dvh - 78px))}#properties{padding:12px}.prop-top{padding:4px 10px}#properties h2{font-size:16px}.floating-panel,#clipPanel{inset:60px 8px auto auto;width:min(320px,calc(100% - 16px));max-height:calc(100% - 168px)}#pgs-camera-menu{top:60px;left:8px}#sceneLoading{top:66px;font-size:13px;width:max-content}#pgs-atlas-zoom{right:10px}
 .right{bottom:var(--pgs-caption-offset,112px)}#modelArea.pgs-props-open #stage{bottom:var(--pgs-props-reserved,0px)}
 .drawingbar{padding:8px 10px}.drawingbar span{font-size:12px}.drawinglayout{display:flex;flex-direction:column}#drawingList{max-height:160px;padding:8px;display:block}.pgs-drawing-search{font-size:16px;margin-bottom:4px}#pgs-source-results{display:flex;gap:6px;overflow:auto;max-height:100px}#drawingList .source-link{min-width:180px;max-width:240px;flex:none;margin:0;padding:8px;font-size:13px}.drawingbody{padding:10px;overflow:auto;display:block}.drawingbody h2{font-size:14px}.pgs-drawing-viewport{max-height:none;min-height:240px}#drawingResource .pgs-drawing-viewport img{min-height:240px}.pgs-drawing-actions{gap:4px}#pgs-drawing-sheet header{padding:8px}.pgs-documents-search{margin-top:6px}
}
@media(max-width:800px) and (max-height:520px){.topbar{height:46px}#album{height:calc(100dvh - 46px)}.left{top:46px}.scene-caption{max-width:60%;right:auto}.right{inset:60px 8px 8px auto;width:310px;max-height:none}.drawinglayout{display:grid;grid-template-columns:190px minmax(0,1fr)}#drawingList{max-height:none}#pgs-source-results{display:block;max-height:none}#drawingList .source-link{min-width:0;max-width:none;width:100%;margin-bottom:4px}#drawingPanel{top:46px}}
@media(max-width:800px) and (max-height:520px){#modelArea.pgs-props-open #stage{bottom:0;right:326px}}
@media(prefers-reduced-motion:reduce){.spinner{animation:none}}
`;
