"use client";

import { AlertTriangle, ClipboardList, FileText, Landmark, TimerReset } from "lucide-react";
import React from "react";
import { buildChangeOrdersIntelligence, type ChangeOrderTone } from "@/lib/change-orders-intelligence";
import type { BudgetItem, Material, Payment, ProcurementRequest, Project, Risk, ScheduleItem } from "@/lib/types";

type Props = { project: Partial<Project>; budgetItems: BudgetItem[]; scheduleItems: ScheduleItem[]; materials: Material[]; procurementRequests: ProcurementRequest[]; payments: Payment[]; risks: Risk[]; onNavigate: (tab: string) => void };
function badge(tone: ChangeOrderTone) { return tone === "good" ? "green" : tone === "warn" ? "yellow" : tone === "bad" ? "red" : tone === "info" ? "blue" : "gray"; }
function money(value: number) { return value ? `${Math.round(value).toLocaleString("ru-RU")} ₽` : "нужна оценка"; }

export function ChangeOrdersWorkspace(props: Props) {
  const model = buildChangeOrdersIntelligence(props);
  const summary = model.summary;
  return <section className="quality-issues-workspace change-orders-workspace" aria-label="Change Orders and Variations">
    <div className={`quality-issues-header tone-${summary.tone}`}><div><div className="eyebrow">Change Orders &amp; Variations</div><h3>Допработы, изменения ВОР и влияние на проект</h3><p>Реестр кандидатов на изменение из ВОР, графика, материалов и рисков. Он не меняет договор, бюджет, КС или cashflow.</p><div className="quality-issues-badges"><span className={`badge ${badge(summary.tone)}`}>{summary.headline}</span><span className="badge blue">к оценке {money(summary.estimatedAmount)}</span><span className="badge gray">сроки {summary.scheduleImpactDays} дн.</span></div></div><div className="quality-issues-actions"><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("Договор / Тендер")}><FileText size={16} />Договор</button><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("КС")}><Landmark size={16} />КС</button></div></div>
    <div className="quality-issues-grid metrics"><Metric title="Candidates" value={String(summary.candidateCount)} detail="изменений к review" tone={summary.tone} /><Metric title="Estimated impact" value={money(summary.estimatedAmount)} detail="не цена допсоглашения" tone={summary.tone} /><Metric title="Schedule impact" value={`${summary.scheduleImpactDays} дн.`} detail="по текущему графику" tone={summary.scheduleImpactDays ? "warn" : "good"} /><Metric title="Contract review" value={summary.contractReviewRequired ? "нужен" : "не нужен"} detail={`${summary.unpricedCount} без цены`} tone={summary.contractReviewRequired ? "warn" : "good"} /></div>
    <div className="quality-issues-grid"><article className="quality-issues-card wide"><div className="section-title"><ClipboardList size={18} /><h4>Variation register</h4></div><div className="table-wrap"><table><thead><tr><th>Кандидат</th><th>Источник</th><th className="numeric">Оценка</th><th className="numeric">Срок</th></tr></thead><tbody>{model.candidates.length ? model.candidates.map((item) => <tr key={item.id}><td><button className={`quality-issue-item tone-${item.tone}`} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><small>{item.rationale}</small></button></td><td>{item.source}</td><td className="numeric">{money(item.estimatedAmount)}</td><td className="numeric">{item.estimatedDelayDays ? `${item.estimatedDelayDays} дн.` : "-"}</td></tr>) : <tr><td colSpan={4}>Кандидатов пока нет. Зафиксируйте изменения в ВОР, графике или реестре рисков.</td></tr>}</tbody></table></div></article><article className="quality-issues-card"><div className="section-title"><AlertTriangle size={18} /><h4>Impact signals</h4></div><p className="quality-issues-handoff-copy">{summary.nextStep}</p><div className="quality-issues-badges"><span className={`badge ${badge(summary.tone)}`}>{summary.candidateCount} к review</span><span className="badge gray">{summary.unpricedCount} без цены</span></div></article><article className="quality-issues-card"><div className="section-title"><TimerReset size={18} /><h4>Approval actions</h4></div><div className="quality-issues-action-list">{model.actions.map((item) => <button className={`quality-issues-action priority-${item.priority}`} key={item.title} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><span>{item.ownerRole} · {item.detail}</span></button>)}</div></article><article className="quality-issues-card wide"><div className="section-title"><AlertTriangle size={18} /><h4>Ограничения v1</h4></div><ul className="quality-issues-limitations">{model.limitations.map((item) => <li key={item}>{item}</li>)}</ul></article></div>
  </section>;
}

function Metric({ title, value, detail, tone }: { title: string; value: string; detail: string; tone: ChangeOrderTone }) { return <div className={`quality-issues-card metric tone-${tone}`}><small>{title}</small><strong>{value}</strong><span>{detail}</span></div>; }
