"use client";

import { AlertTriangle, FileCheck2, FileText, Gavel, Scale } from "lucide-react";
import React from "react";
import { buildClaimsNoticesIntelligence, type ClaimsNoticesTone, type NoticeReadiness } from "@/lib/claims-notices-intelligence";
import type { DocumentChecklistItem } from "@/lib/project-pipeline";
import type { BudgetItem, Material, Payment, ProcurementRequest, Project, ProjectDocument, Risk, ScheduleItem } from "@/lib/types";

type Props = { project: Partial<Project>; budgetItems: BudgetItem[]; scheduleItems: ScheduleItem[]; materials: Material[]; procurementRequests: ProcurementRequest[]; payments: Payment[]; risks: Risk[]; documents: ProjectDocument[]; documentChecklist: DocumentChecklistItem[]; onNavigate: (tab: string) => void };
function badge(tone: ClaimsNoticesTone) { return tone === "good" ? "green" : tone === "warn" ? "yellow" : tone === "bad" ? "red" : tone === "info" ? "blue" : "gray"; }
function readinessLabel(value: NoticeReadiness) { return value === "draft_ready" ? "черновик готов" : value === "needs_evidence" ? "нужны доказательства" : "проверить договор"; }
function money(value: number) { return value ? `${Math.round(value).toLocaleString("ru-RU")} ₽` : "нужна оценка"; }

export function ClaimsNoticesWorkspace(props: Props) {
  const model = buildClaimsNoticesIntelligence(props);
  const summary = model.summary;
  return <section className="quality-issues-workspace claims-notices-workspace" aria-label="Claims and Notices Intelligence">
    <div className={`quality-issues-header tone-${summary.tone}`}><div><div className="eyebrow">Claims &amp; Notices</div><h3>Уведомления, претензии и договорные сроки</h3><p>Реестр оснований для управленческого и юридического review. Ничего не отправляется и не создает обязательств без отдельного подтверждения.</p><div className="quality-issues-badges"><span className={`badge ${badge(summary.tone)}`}>{summary.headline}</span><span className="badge blue">доказательств {summary.evidenceDocuments}</span><span className="badge gray">к оценке {money(summary.estimatedAmount)}</span></div></div><div className="quality-issues-actions"><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("Документы")}><FileCheck2 size={16} />Доказательства</button><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("Риски")}><AlertTriangle size={16} />Риски</button></div></div>
    <div className="quality-issues-grid metrics"><Metric title="Notice candidates" value={String(summary.noticeCount)} detail="к договорному review" tone={summary.tone} /><Metric title="Urgent" value={String(summary.urgentCount)} detail="приоритетных оснований" tone={summary.urgentCount ? "bad" : "good"} /><Metric title="Evidence" value={String(summary.evidenceDocuments)} detail="документов и чеклистов" tone={summary.evidenceDocuments ? "good" : "warn"} /><Metric title="Contract review" value={summary.contractReviewRequired ? "нужен" : "нет"} detail={`${summary.scheduleImpactDays} дн. влияния`} tone={summary.contractReviewRequired ? "warn" : "good"} /></div>
    <div className="quality-issues-grid"><article className="quality-issues-card wide"><div className="section-title"><Gavel size={18} /><h4>Notice register</h4></div><div className="table-wrap"><table><thead><tr><th>Основание</th><th>Готовность</th><th className="numeric">Оценка</th><th>Доказательства</th></tr></thead><tbody>{model.notices.length ? model.notices.map((notice) => <tr key={notice.id}><td><button className={`quality-issue-item tone-${notice.priority === "urgent" ? "bad" : "warn"}`} type="button" onClick={() => props.onNavigate(notice.targetTab)}><strong>{notice.title}</strong><small>{notice.trigger}</small></button></td><td><span className="badge yellow">{readinessLabel(notice.readiness)}</span></td><td className="numeric">{money(notice.estimatedAmount)}</td><td>{notice.evidence[0]}</td></tr>) : <tr><td colSpan={4}>Оснований пока нет. Фиксируйте изменения, задержки и переписку до истечения договорных сроков.</td></tr>}</tbody></table></div></article><article className="quality-issues-card"><div className="section-title"><Scale size={18} /><h4>Draft guidance</h4></div><p className="quality-issues-handoff-copy">{model.notices[0]?.draftText ?? summary.nextStep}</p><span className="muted">Текст предназначен для review, а не для автоматической отправки.</span></article><article className="quality-issues-card"><div className="section-title"><FileText size={18} /><h4>Preparation actions</h4></div><div className="quality-issues-action-list">{model.actions.map((action) => <button className={`quality-issues-action priority-${action.priority}`} key={action.title} type="button" onClick={() => props.onNavigate(action.targetTab)}><strong>{action.title}</strong><span>{action.ownerRole} · {action.detail}</span></button>)}</div></article><article className="quality-issues-card wide"><div className="section-title"><AlertTriangle size={18} /><h4>Ограничения v1</h4></div><ul className="quality-issues-limitations">{model.limitations.map((item) => <li key={item}>{item}</li>)}</ul></article></div>
  </section>;
}

function Metric({ title, value, detail, tone }: { title: string; value: string; detail: string; tone: ClaimsNoticesTone }) { return <div className={`quality-issues-card metric tone-${tone}`}><small>{title}</small><strong>{value}</strong><span>{detail}</span></div>; }
