"use client";

import { AlertTriangle, Landmark, ListChecks, TrendingDown, WalletCards } from "lucide-react";
import React from "react";
import { buildCostToCompleteIntelligence, type CostForecastTone } from "@/lib/cost-to-complete-intelligence";
import type { BudgetItem, Material, Payment, ProcurementRequest, Project, Risk, ScheduleItem } from "@/lib/types";

type Props = { project: Partial<Project>; budgetItems: BudgetItem[]; scheduleItems: ScheduleItem[]; materials: Material[]; procurementRequests: ProcurementRequest[]; payments: Payment[]; risks: Risk[]; onNavigate: (tab: string) => void };
function badge(tone: CostForecastTone) { return tone === "good" ? "green" : tone === "warn" ? "yellow" : tone === "bad" ? "red" : tone === "info" ? "blue" : "gray"; }
function money(value: number) { return `${Math.round(value).toLocaleString("ru-RU")} ₽`; }

export function CostToCompleteWorkspace(props: Props) {
  const model = buildCostToCompleteIntelligence(props);
  const summary = model.summary;
  return <section className="quality-issues-workspace cost-to-complete-workspace" aria-label="Cost to Complete and Margin Forecast">
    <div className={`quality-issues-header tone-${summary.tone}`}><div><div className="eyebrow">Cost-to-Complete &amp; Margin Forecast</div><h3>Прогноз затрат до завершения и маржи</h3><p>Управленческий прогноз из ВОР, графика, снабжения и платежей. Он не создает проводок и не меняет рабочие данные.</p><div className="quality-issues-badges"><span className={`badge ${badge(summary.tone)}`}>{summary.headline}</span><span className="badge blue">{summary.completionPercent.toFixed(0)}% факт работ</span><span className="badge gray">остаток {money(summary.costToComplete)}</span></div></div><div className="quality-issues-actions"><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("Бюджет / ВОР")}><TrendingDown size={16} />ВОР</button><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("График")}><ListChecks size={16} />График</button></div></div>
    <div className="quality-issues-grid metrics"><Metric title="Forecast cost" value={money(summary.forecastCost)} detail={`план ${money(summary.plannedCost)}`} tone={summary.tone} /><Metric title="До завершения" value={money(summary.costToComplete)} detail={`${summary.remainingWorkPercent.toFixed(0)}% работ осталось`} tone={summary.tone} /><Metric title="Forecast margin" value={`${summary.forecastMarginPercent.toFixed(1)}%`} detail={money(summary.forecastMargin)} tone={summary.forecastMarginPercent < 5 ? "bad" : summary.tone} /><Metric title="Liquidity" value={summary.cashGap < 0 ? money(summary.cashGap) : "без разрыва"} detail={`need ${money(summary.financingNeed)}`} tone={summary.cashGap < 0 ? "bad" : "good"} /></div>
    <div className="quality-issues-grid"><article className="quality-issues-card wide"><div className="section-title"><Landmark size={18} /><h4>Cost forecast by category</h4></div><div className="table-wrap"><table><thead><tr><th>Категория</th><th className="numeric">План</th><th className="numeric">Факт</th><th className="numeric">Forecast</th><th className="numeric">Отклонение</th></tr></thead><tbody>{model.categories.length ? model.categories.map((item) => <tr key={item.key}><td><span className={`badge ${badge(item.tone)}`}>{item.label}</span></td><td className="numeric">{money(item.planned)}</td><td className="numeric">{money(item.actual)}</td><td className="numeric">{money(item.forecast)}</td><td className="numeric">{item.deviation > 0 ? "+" : ""}{money(item.deviation)}</td></tr>) : <tr><td colSpan={5}>ВОР пока не загружен: прогноз не рассчитывается.</td></tr>}</tbody></table></div></article><article className="quality-issues-card"><div className="section-title"><AlertTriangle size={18} /><h4>Forecast signals</h4></div><div className="quality-issues-list">{model.signals.length ? model.signals.map((item) => <button className={`quality-issue-item tone-${item.tone}`} key={item.id} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><small>{item.detail}</small></button>) : <span className="muted">Критичных сигналов в доступном срезе нет.</span>}</div></article><article className="quality-issues-card"><div className="section-title"><WalletCards size={18} /><h4>Margin protection actions</h4></div><div className="quality-issues-action-list">{model.actions.map((item) => <button className={`quality-issues-action priority-${item.priority}`} key={item.title} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><span>{item.ownerRole} · {item.detail}</span></button>)}</div></article><article className="quality-issues-card wide"><div className="section-title"><AlertTriangle size={18} /><h4>Ограничения v1</h4></div><p className="quality-issues-handoff-copy">{summary.nextStep}</p><ul className="quality-issues-limitations">{model.limitations.map((item) => <li key={item}>{item}</li>)}</ul></article></div>
  </section>;
}
function Metric({ title, value, detail, tone }: { title: string; value: string; detail: string; tone: CostForecastTone }) { return <div className={`quality-issues-card metric tone-${tone}`}><small>{title}</small><strong>{value}</strong><span>{detail}</span></div>; }
