"use client";

import { ClipboardCheck, FileText, HardHat, ShieldCheck } from "lucide-react";
import React from "react";
import { buildHseSafetyPermitIntelligence, type HseTone } from "@/lib/hse-safety-permit-intelligence";
import type { DocumentChecklistItem } from "@/lib/project-pipeline";
import type { DailyReport, Project, ProjectDocument, Risk, ScheduleItem } from "@/lib/types";

type Props = { project: Partial<Project>; scheduleItems: ScheduleItem[]; dailyReports: DailyReport[]; risks: Risk[]; documents: ProjectDocument[]; documentChecklist: DocumentChecklistItem[]; onNavigate: (tab: string) => void };
function badge(tone: HseTone) { return tone === "good" ? "green" : tone === "warn" ? "yellow" : tone === "bad" ? "red" : tone === "info" ? "blue" : "gray"; }

export function HseSafetyPermitWorkspace(props: Props) {
  const model = buildHseSafetyPermitIntelligence(props);
  return <section className="quality-issues-workspace hse-safety-workspace" aria-label="HSE Safety and Permit Compliance">
    <div className={`quality-issues-header tone-${model.summary.tone}`}><div><div className="eyebrow">HSE / Safety &amp; Permit Compliance</div><h3>ОТиПБ / Допуски</h3><p>Контроль HSE-сигналов, разрешительной документации и условий безопасного выполнения работ.</p><div className="quality-issues-badges"><span className={`badge ${badge(model.summary.tone)}`}>{model.summary.headline}</span><span className="badge blue">{model.summary.totalSignals} signals</span><span className="badge gray">{model.summary.permitBlockers} permit blockers</span></div></div><div className="quality-issues-actions"><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("Рапорты")}><ClipboardCheck size={16} />Рапорты</button><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("Документы")}><FileText size={16} />Документы</button></div></div>
    <div className="quality-issues-grid metrics"><Metric title="HSE status" value={model.summary.status} detail={model.summary.nextStep} tone={model.summary.tone} /><Metric title="Сигналы" value={String(model.summary.totalSignals)} detail={`${model.summary.criticalSignals} critical`} tone={model.summary.criticalSignals ? "bad" : model.summary.totalSignals ? "warn" : "good"} /><Metric title="Документы HSE" value={String(model.summary.safetyDocuments)} detail="инструктажи / допуски / permits" tone={model.summary.safetyDocuments ? "info" : "neutral"} /><Metric title="Permit blockers" value={String(model.summary.permitBlockers)} detail="требуют подтверждения" tone={model.summary.permitBlockers ? "bad" : "good"} /></div>
    <div className="quality-issues-grid"><article className="quality-issues-card wide"><div className="section-title"><HardHat size={18} /><h4>HSE signal register</h4></div><div className="quality-issues-list">{model.signals.length ? model.signals.map((item) => <button className={`quality-issue-item tone-${item.tone}`} key={item.id} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><span>{item.source} · {item.severity}</span><small>{item.detail}</small><em>{item.nextAction}</em></button>) : <span className="muted">HSE-сигналы появятся из рапортов, рисков, графика и документов проекта.</span>}</div></article><article className="quality-issues-card"><div className="section-title"><ShieldCheck size={18} /><h4>Safety actions</h4></div><div className="quality-issues-action-list">{model.actions.map((item) => <button className={`quality-issues-action priority-${item.priority}`} key={item.title} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><span>{item.ownerRole} · {item.detail}</span></button>)}</div></article><article className="quality-issues-card"><div className="section-title"><ClipboardCheck size={18} /><h4>{model.handoff.title}</h4></div><pre className="quality-issues-handoff-copy">{model.handoff.copyText}</pre></article><article className="quality-issues-card wide"><div className="section-title"><FileText size={18} /><h4>Ограничения v1</h4></div><ul className="quality-issues-limitations">{model.limitations.map((item) => <li key={item}>{item}</li>)}</ul></article></div>
  </section>;
}
function Metric({ title, value, detail, tone }: { title: string; value: string; detail: string; tone: HseTone }) { return <div className={`quality-issues-card metric tone-${tone}`}><small>{title}</small><strong>{value}</strong><span>{detail}</span></div>; }
