"use client";

import { ClipboardList, HardHat, TimerReset, Users, Wrench } from "lucide-react";
import React from "react";
import { buildResourcesEquipmentIntelligence, type ResourcesEquipmentTone } from "@/lib/resources-equipment-intelligence";
import type { DailyReport, Project, ScheduleItem } from "@/lib/types";

type Props = { project: Partial<Project>; dailyReports: DailyReport[]; scheduleItems: ScheduleItem[]; onNavigate: (tab: string) => void };
function badge(tone: ResourcesEquipmentTone) { return tone === "good" ? "green" : tone === "warn" ? "yellow" : tone === "bad" ? "red" : tone === "info" ? "blue" : "gray"; }

export function ResourcesEquipmentWorkspace(props: Props) {
  const model = buildResourcesEquipmentIntelligence(props);
  return <section className="quality-issues-workspace resources-equipment-workspace" aria-label="Resources and Equipment Intelligence">
    <div className={`quality-issues-header tone-${model.summary.tone}`}><div><div className="eyebrow">Resources &amp; Equipment Intelligence</div><h3>Люди / Техника / Простои</h3><p>Срез численности, ИТР, задействованной техники и простоев по ежедневным рапортам с привязкой к графику.</p><div className="quality-issues-badges"><span className={`badge ${badge(model.summary.tone)}`}>{model.summary.headline}</span><span className="badge blue">{model.summary.reportCount} рапортов</span><span className="badge gray">{model.summary.equipmentUnits} техники</span></div></div><div className="quality-issues-actions"><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("Рапорты")}><ClipboardList size={16} />Рапорты</button><button className="button secondary compact-button" type="button" onClick={() => props.onNavigate("График")}><TimerReset size={16} />График</button></div></div>
    <div className="quality-issues-grid metrics"><Metric title="Resource status" value={model.summary.status} detail={model.summary.nextStep} tone={model.summary.tone} /><Metric title="Последняя смена" value={`${model.summary.latestWorkers}/${model.summary.latestEngineers}`} detail={`рабочие / ИТР · среднее ${model.summary.averageWorkers}/${model.summary.averageEngineers}`} tone={model.summary.reportCount ? "info" : "neutral"} /><Metric title="Техника" value={String(model.summary.equipmentUnits)} detail={`${model.summary.equipmentDowntimeReports} простоев техники`} tone={model.summary.equipmentDowntimeReports ? "bad" : model.summary.equipmentUnits ? "info" : "neutral"} /><Metric title="График" value={String(model.summary.stoppedWorks)} detail="остановленных фронтов" tone={model.summary.stoppedWorks ? "bad" : "good"} /></div>
    <div className="quality-issues-grid"><article className="quality-issues-card wide"><div className="section-title"><HardHat size={18} /><h4>Equipment register</h4></div><div className="quality-issues-list">{model.equipment.length ? model.equipment.map((item) => <div className={`quality-issue-item tone-${item.tone}`} key={item.name}><strong>{item.name}</strong><span>{item.mentions} упоминаний · последний рапорт {item.lastSeen}</span></div>) : <span className="muted">Техника появится после заполнения ежедневного рапорта.</span>}</div></article><article className="quality-issues-card"><div className="section-title"><Wrench size={18} /><h4>Resource signals</h4></div><div className="quality-issues-list">{model.signals.length ? model.signals.map((item) => <button className={`quality-issue-item tone-${item.tone}`} key={item.id} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><span>{item.source}</span><small>{item.detail}</small><em>{item.nextAction}</em></button>) : <span className="muted">Нет ресурсных сигналов в доступных рапортах.</span>}</div></article><article className="quality-issues-card"><div className="section-title"><Users size={18} /><h4>Recovery actions</h4></div><div className="quality-issues-action-list">{model.actions.map((item) => <button className={`quality-issues-action priority-${item.priority}`} key={item.title} type="button" onClick={() => props.onNavigate(item.targetTab)}><strong>{item.title}</strong><span>{item.ownerRole} · {item.detail}</span></button>)}</div></article><article className="quality-issues-card"><div className="section-title"><ClipboardList size={18} /><h4>{model.handoff.title}</h4></div><pre className="quality-issues-handoff-copy">{model.handoff.copyText}</pre></article><article className="quality-issues-card wide"><div className="section-title"><Wrench size={18} /><h4>Ограничения v1</h4></div><ul className="quality-issues-limitations">{model.limitations.map((item) => <li key={item}>{item}</li>)}</ul></article></div>
  </section>;
}
function Metric({ title, value, detail, tone }: { title: string; value: string; detail: string; tone: ResourcesEquipmentTone }) { return <div className={`quality-issues-card metric tone-${tone}`}><small>{title}</small><strong>{value}</strong><span>{detail}</span></div>; }
